

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clock-in-app-container
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: clock-in-db-container
    restart: always
    environment:
      MYSQL_DATABASE: clock_in_db
      MYSQL_USER: clock_in_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: clock-in-phpmyadmin-container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: clock_in_user
      PMA_PASSWORD: password
    depends_on:
      - db

volumes:
  db-data: